# Generated by Django 5.1.2 on 2025-02-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_story_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
